title: <p align="center"> Yash Kumar Roy </p>
logo: /image/dp.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/yashkumarroy21/">LinkedIn</a> |
  <a href="https://github.com/SpidY21">GitHub</a>
  
  <br>   
  Looking for a Data Science role.
  Worked on some related project.
  <br>
  </p>



theme: jekyll-theme-minimal
